#!/bin/sh

echo "Enter number to find fibonacci up until:"
read N
a=0
b=1  
i=0
echo "The Fibonacci series is :"
echo "$a"
echo "$b"
  
while [ $i -lt $((N-2)) ] 
do
sum=$((a+b))
a=$((b))
b=$((sum))
i=$((i+1))
echo "$b"
done
