#!/bin/sh/
echo "enter the file name: \c"
read file
if (!-f "$file")
then
echo "file is not valid"
exit 1
fi
echo "The number of lines in a file: "
wc -l "$file"
echo "The number of words in a file: "
wc -w "$file"
echo "The number of characters in a file: "
wc -c "$file"
